CUDA_VISIBLE_DEVICES=0 python3 main.py \
    --do_train \
    --train_file /home/aurobit/llm/data/chatglm-6b/minimal/train.json \
    --validation_file /home/aurobit/llm/data/chatglm-6b/minimal/dev.json \
    --prompt_column prompt \
    --response_column response \
    --history_column history \
    --overwrite_cache \
    --model_name_or_path /home/aurobit/llm/model/chatglm-6b \
    --output_dir output \
    --overwrite_output_dir \
    --max_source_length 1024 \
    --max_target_length 128 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 16 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 20000 \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 1e-4 \
    --pre_seq_len 128 \
    --quantization_bit 4
